name: mybasketteam
description: "A Flutter app for managing basketball team players"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  # State management
  flutter_riverpod: ^2.4.9
  
  # Navigation
  go_router: ^13.2.0
  
  # UI components
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  
  # Utils
  uuid: ^4.2.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
